homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 49
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  server_port: 8123
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: home:8123
  #ssl_certificate: /etc/letsencrypt/live/home.volker-boehme.de/fullchain.pem
  #ssl_key: /etc/letsencrypt/live/home.volker-boehme.de/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:

#default config:
default_config:

# Configuration panel
config:

# Discover some devices automatically
discovery:

#person
person: 

# Allows you to issue voice commands from the frontend in enabled browsers
#intent_script: !include intent_script.yaml

#conversation: !include conversation.yaml

# Enables support for tracking state changes over time.
history:

#history_graph: !include history_graph.yaml

# View all events in a logbook
logbook:

# Map
map:

# Track the sun
sun:

# Weather Prediction
weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml

device_tracker: !include devicetracker.yaml
owntracks: !include owntracks.yaml

zwave:
  #usb_path: /dev/zwave
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key
#  autoheal: false

telegram_bot: !include telegram.yaml
matrix: !include matrix.yaml
notify: !include notify.yaml

group: !include_dir_merge_named groups

panel_iframe: !include paneliframe.yaml

mqtt: !include mqtt.yaml

# This will override the default home zone
zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: Work Volker
  latitude: !secret work_volker_latitude
  longitude: !secret work_volker_longitude
  icon: mdi:domain

zone 3:
  name: Parents Volker
  latitude: !secret parents_volker_latitude
  longitude: !secret parents_volker_longitude
  icon: mdi:home-outline

zone 4:
  name: Work Katrin
  latitude: !secret work_katrin_latitude
  longitude: !secret work_katrin_longitude
  icon: mdi:domain

zone 5:
  name: Parents Katrin
  latitude: !secret parents_katrin_latitude
  longitude: !secret parents_katrin_longitude
  icon: mdi:home-outline

automation old: !include_dir_merge_list automation
automation: !include automations.yaml

input_number: !include input_number.yaml

input_boolean: !include input_boolean.yaml

#input_select: !include input_select.yaml

input_datetime: !include input_datetime.yaml

logger:
  default: info

vacuum: !include vacuum.yaml

recorder:
  purge_interval: 1
  purge_keep_days: 10
  db_url: !secret mariadb

homematic: !include homematic.yaml

influxdb: !include influxdb.yaml

script: !include scripts.yaml

cloud:

calendar: !include calendar.yaml

hue:
  bridges:
    - host: 192.168.178.97
      allow_unreachable: true
      allow_hue_groups: false

system_health:

utility_meter: !include utilitymeter.yaml
