#homeassistant:
#  # Name of the location where Home Assistant is running
#  name: Home
  # Location required to calculate the time the sun rises and sets
#  latitude: !secret home_latitude
#  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
#  elevation: 49
  # metric for Metric, imperial for Imperial
#  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#  time_zone: Europe/Berlin
#  auth_providers:
#   - type: homeassistant
#   - type: legacy_api_password
#     api_password: !secret http_password
#  external_url: "https://home-assistant.lan"
#  internal_url: "https://home-assistant.lan"

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  server_port: 8123
  # Uncomment this if you are using SSL or running in Docker etc
#  base_url: https://home-assistant.lan
  #ssl_certificate: /etc/letsencrypt/live/home.volker-boehme.de/fullchain.pem
  #ssl_key: /etc/letsencrypt/live/home.volker-boehme.de/privkey.pem
#  ip_ban_enabled: True
#  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/16
    - 172.17.0.0/16
    - 192.168.0.0/16
    - 127.0.0.1
    - ::1
    - fe80::/64
    - fe00::/64
    - fd00::/64
    - fd73:ceae:f91c::/48
    - fd84:ceae:f91c::/48
    - fd62:ceae:f91c::/48
 
#default config:
default_config:

# Configuration panel
config:

#person
person: 

# Allows you to issue voice commands from the frontend in enabled browsers
#intent_script: !include intent_script.yaml

#conversation: !include conversation.yaml

# Enables support for tracking state changes over time.
history:

#history_graph: !include history_graph.yaml

# View all events in a logbook
logbook:

# Map
map:

# Track the sun
#sun:

# Weather Prediction
#weather:
#  - platform: darksky
#    api_key: !secret dark_sky_api_key

sensor: !include sensor.yaml
#binary_sensor: !include binary_sensor.yaml

device_tracker: !include devicetracker.yaml
owntracks: !include owntracks.yaml

#zwave:
  #usb_path: /dev/zwave
#  usb_path: /dev/ttyACM0
#  device_config: !include zwave_device_config.yaml
#  network_key: !secret zwave_network_key
#  autoheal: false

telegram_bot: !include telegram.yaml
#matrix: !include matrix.yaml
notify: !include notify.yaml

group: !include_dir_merge_named groups

panel_iframe: !include paneliframe.yaml

#mqtt: !include mqtt.yaml

# This will override the default home zone
#zone: !include zone.yaml

automation old: !include_dir_merge_list automation
automation: !include automations.yaml

input_number: !include input_number.yaml

input_boolean: !include input_boolean.yaml

#input_select: !include input_select.yaml

input_datetime: !include input_datetime.yaml

logger:
  default: info
#  logs:
#    homeassistant.components.websocket_api.http.connection: debug
  
recorder:
  purge_keep_days: 10
  db_url: !secret mariadb

#homematic: !include homematic.yaml

script: !include scripts.yaml

cloud:

calendar: !include calendar.yaml

#hue:
#  bridges:
#    - host: 192.168.101.253
#      allow_unreachable: true
#      allow_hue_groups: false

system_health:

utility_meter: !include utilitymeter.yaml

#media_player: !include mediaplayer.yaml

graphite: 
  host: graphite

prometheus:
 
statsd:
  host: sensu-agent

#miele: 
#  client_id: !secret miele_client_id
#  client_secret: !secret miele_client_secret

