##Start## lisacover
config_blinds_lisacover:
  name: Config Blinds lisacover
  view: no
  entities:
    - input_boolean.control_blinds_lisacover_use_pd_on_close
    - input_boolean.control_blinds_lisacover_openblinds
    - input_boolean.control_blinds_lisacover_closeblinds
    - input_boolean.control_blinds_lisacover_cooldown_during_night
    - input_boolean.control_blinds_lisacover_sunsetsunrise
    - input_datetime.control_blinds_lisacover_offset_blinds_up_weekend
    - input_datetime.control_blinds_lisacover_cooldown_during_night_open
    - input_datetime.control_blinds_lisacover_cooldown_during_night_close
    - input_datetime.control_blinds_lisacover_earliest_time_blinds_up
    - input_datetime.control_blinds_lisacover_latest_time_blinds_down
    - input_datetime.control_blinds_lisacover_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_lisacover_openblinds_on_time
    - input_datetime.control_blinds_lisacover_closeblinds_on_time
    - input_number.control_blinds_lisacover_cooldown_night_blinds_position
##End## lisacover

##Start## mariecover
config_blinds_mariecover:
  name: Config Blinds mariecover
  view: no
  entities:
    - input_boolean.control_blinds_mariecover_use_pd_on_close
    - input_boolean.control_blinds_mariecover_openblinds
    - input_boolean.control_blinds_mariecover_closeblinds
    - input_boolean.control_blinds_mariecover_cooldown_during_night
    - input_boolean.control_blinds_mariecover_sunsetsunrise
    - input_datetime.control_blinds_mariecover_offset_blinds_up_weekend
    - input_datetime.control_blinds_mariecover_cooldown_during_night_open
    - input_datetime.control_blinds_mariecover_cooldown_during_night_close
    - input_datetime.control_blinds_mariecover_earliest_time_blinds_up
    - input_datetime.control_blinds_mariecover_latest_time_blinds_down
    - input_datetime.control_blinds_mariecover_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_mariecover_openblinds_on_time
    - input_datetime.control_blinds_mariecover_closeblinds_on_time
    - input_number.control_blinds_mariecover_cooldown_night_blinds_position
##End## mariecover

##Start## kitchen_level
config_blinds_kitchen_level:
  name: Config Blinds kitchen_level
  view: no
  entities:
    - input_boolean.control_blinds_kitchen_level_use_pd_on_close
    - input_boolean.control_blinds_kitchen_level_openblinds
    - input_boolean.control_blinds_kitchen_level_closeblinds
    - input_boolean.control_blinds_kitchen_level_cooldown_during_night
    - input_boolean.control_blinds_kitchen_level_sunsetsunrise
    - input_datetime.control_blinds_kitchen_level_offset_blinds_up_weekend
    - input_datetime.control_blinds_kitchen_level_cooldown_during_night_open
    - input_datetime.control_blinds_kitchen_level_cooldown_during_night_close
    - input_datetime.control_blinds_kitchen_level_earliest_time_blinds_up
    - input_datetime.control_blinds_kitchen_level_latest_time_blinds_down
    - input_datetime.control_blinds_kitchen_level_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_kitchen_level_openblinds_on_time
    - input_datetime.control_blinds_kitchen_level_closeblinds_on_time
    - input_number.control_blinds_kitchen_level_cooldown_night_blinds_position
##End## kitchen_level

##Start## guest_room_level
config_blinds_guest_room_level:
  name: Config Blinds guest_room_level
  view: no
  entities:
    - input_boolean.control_blinds_guest_room_level_use_pd_on_close
    - input_boolean.control_blinds_guest_room_level_openblinds
    - input_boolean.control_blinds_guest_room_level_closeblinds
    - input_boolean.control_blinds_guest_room_level_cooldown_during_night
    - input_boolean.control_blinds_guest_room_level_sunsetsunrise
    - input_datetime.control_blinds_guest_room_level_offset_blinds_up_weekend
    - input_datetime.control_blinds_guest_room_level_cooldown_during_night_open
    - input_datetime.control_blinds_guest_room_level_cooldown_during_night_close
    - input_datetime.control_blinds_guest_room_level_earliest_time_blinds_up
    - input_datetime.control_blinds_guest_room_level_latest_time_blinds_down
    - input_datetime.control_blinds_guest_room_level_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_guest_room_level_openblinds_on_time
    - input_datetime.control_blinds_guest_room_level_closeblinds_on_time
    - input_number.control_blinds_guest_room_level_cooldown_night_blinds_position
##End## guest_room_level

##Start## living_room_window_level
config_blinds_living_room_window_level:
  name: Config Blinds living_room_window_level
  view: no
  entities:
    - input_boolean.control_blinds_living_room_window_level_use_pd_on_close
    - input_boolean.control_blinds_living_room_window_level_openblinds
    - input_boolean.control_blinds_living_room_window_level_closeblinds
    - input_boolean.control_blinds_living_room_window_level_cooldown_during_night
    - input_boolean.control_blinds_living_room_window_level_sunsetsunrise
    - input_datetime.control_blinds_living_room_window_level_offset_blinds_up_weekend
    - input_datetime.control_blinds_living_room_window_level_cooldown_during_night_open
    - input_datetime.control_blinds_living_room_window_level_cooldown_during_night_close
    - input_datetime.control_blinds_living_room_window_level_earliest_time_blinds_up
    - input_datetime.control_blinds_living_room_window_level_latest_time_blinds_down
    - input_datetime.control_blinds_living_room_window_level_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_living_room_window_level_openblinds_on_time
    - input_datetime.control_blinds_living_room_window_level_closeblinds_on_time
    - input_number.control_blinds_living_room_window_level_cooldown_night_blinds_position
##End## living_room_window_level

##Start## living_room_door_level
config_blinds_living_room_door_level:
  name: Config Blinds living_room_door_level
  view: no
  entities:
    - input_boolean.control_blinds_living_room_door_level_use_pd_on_close
    - input_boolean.control_blinds_living_room_door_level_openblinds
    - input_boolean.control_blinds_living_room_door_level_closeblinds
    - input_boolean.control_blinds_living_room_door_level_cooldown_during_night
    - input_boolean.control_blinds_living_room_door_level_sunsetsunrise
    - input_datetime.control_blinds_living_room_door_level_offset_blinds_up_weekend
    - input_datetime.control_blinds_living_room_door_level_cooldown_during_night_open
    - input_datetime.control_blinds_living_room_door_level_cooldown_during_night_close
    - input_datetime.control_blinds_living_room_door_level_earliest_time_blinds_up
    - input_datetime.control_blinds_living_room_door_level_latest_time_blinds_down
    - input_datetime.control_blinds_living_room_door_level_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_living_room_door_level_openblinds_on_time
    - input_datetime.control_blinds_living_room_door_level_closeblinds_on_time
    - input_number.control_blinds_living_room_door_level_cooldown_night_blinds_position
##End## living_room_door_level

##Start## parentsbedroom_level
config_blinds_parentsbedroom_level:
  name: Config Blinds parentsbedroom_level
  view: no
  entities:
    - input_boolean.control_blinds_parentsbedroom_level_use_pd_on_close
    - input_boolean.control_blinds_parentsbedroom_level_openblinds
    - input_boolean.control_blinds_parentsbedroom_level_closeblinds
    - input_boolean.control_blinds_parentsbedroom_level_cooldown_during_night
    - input_boolean.control_blinds_parentsbedroom_level_sunsetsunrise
    - input_datetime.control_blinds_parentsbedroom_level_offset_blinds_up_weekend
    - input_datetime.control_blinds_parentsbedroom_level_cooldown_during_night_open
    - input_datetime.control_blinds_parentsbedroom_level_cooldown_during_night_close
    - input_datetime.control_blinds_parentsbedroom_level_earliest_time_blinds_up
    - input_datetime.control_blinds_parentsbedroom_level_latest_time_blinds_down
    - input_datetime.control_blinds_parentsbedroom_level_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_parentsbedroom_level_openblinds_on_time
    - input_datetime.control_blinds_parentsbedroom_level_closeblinds_on_time
    - input_number.control_blinds_parentsbedroom_level_cooldown_night_blinds_position
##End## parentsbedroom_level

##Start## global
config_blinds_global:
  name: Config Blinds global
  view: no
  entities:
    - input_boolean.control_blinds_enable_global
    - input_boolean.control_blinds_enable_pd_global
    - input_boolean.control_blinds_enable_cooldown_during_night_global
    - input_boolean.control_blinds_open_all_blinds_global
    - input_boolean.control_blinds_close_all_blinds_global
    - input_boolean.control_blinds_configuration
##End## global

##Start## config_blinds
config_blinds:
  name: Config Blinds
  view: yes
  entities:
    - group.config_blinds_lisacover
    - group.config_blinds_mariecover
    - group.config_blinds_kitchen_level
    - group.config_blinds_guest_room_level
    - group.config_blinds_living_room_window_level
    - group.config_blinds_living_room_door_level
    - group.config_blinds_parentsbedroom_switch
    - group.config_blinds_parentsbedroom_level
    - group.config_blinds_global
##End## config_blinds
