##Start## mariecover
config_blinds_mariecover:
  name: Config Blinds mariecover
  entities:
    - input_boolean.control_blinds_mariecover_use_pd_on_close
    - input_boolean.control_blinds_mariecover_openblinds
    - input_boolean.control_blinds_mariecover_closeblinds
    - input_boolean.control_blinds_mariecover_cooldown_during_night
    - input_boolean.control_blinds_mariecover_sunsetsunrise
    - input_datetime.control_blinds_mariecover_offset_blinds_up_weekend
    - input_datetime.control_blinds_mariecover_cooldown_during_night_open
    - input_datetime.control_blinds_mariecover_cooldown_during_night_close
    - input_datetime.control_blinds_mariecover_earliest_time_blinds_up
    - input_datetime.control_blinds_mariecover_latest_time_blinds_down
    - input_datetime.control_blinds_mariecover_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_mariecover_openblinds_on_time
    - input_datetime.control_blinds_mariecover_closeblinds_on_time
    - input_number.control_blinds_mariecover_cooldown_night_blinds_position
##End## mariecover

##Start## lisacover
config_blinds_lisacover:
  name: Config Blinds lisacover
  entities:
    - input_boolean.control_blinds_lisacover_use_pd_on_close
    - input_boolean.control_blinds_lisacover_openblinds
    - input_boolean.control_blinds_lisacover_closeblinds
    - input_boolean.control_blinds_lisacover_cooldown_during_night
    - input_boolean.control_blinds_lisacover_sunsetsunrise
    - input_datetime.control_blinds_lisacover_offset_blinds_up_weekend
    - input_datetime.control_blinds_lisacover_cooldown_during_night_open
    - input_datetime.control_blinds_lisacover_cooldown_during_night_close
    - input_datetime.control_blinds_lisacover_earliest_time_blinds_up
    - input_datetime.control_blinds_lisacover_latest_time_blinds_down
    - input_datetime.control_blinds_lisacover_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_lisacover_openblinds_on_time
    - input_datetime.control_blinds_lisacover_closeblinds_on_time
    - input_number.control_blinds_lisacover_cooldown_night_blinds_position
##End## lisacover

##Start## living_room_door
config_blinds_living_room_door:
  name: Config Blinds living_room_door
  entities:
    - input_boolean.control_blinds_living_room_door_use_pd_on_close
    - input_boolean.control_blinds_living_room_door_openblinds
    - input_boolean.control_blinds_living_room_door_closeblinds
    - input_boolean.control_blinds_living_room_door_cooldown_during_night
    - input_boolean.control_blinds_living_room_door_sunsetsunrise
    - input_datetime.control_blinds_living_room_door_offset_blinds_up_weekend
    - input_datetime.control_blinds_living_room_door_cooldown_during_night_open
    - input_datetime.control_blinds_living_room_door_cooldown_during_night_close
    - input_datetime.control_blinds_living_room_door_earliest_time_blinds_up
    - input_datetime.control_blinds_living_room_door_latest_time_blinds_down
    - input_datetime.control_blinds_living_room_door_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_living_room_door_openblinds_on_time
    - input_datetime.control_blinds_living_room_door_closeblinds_on_time
    - input_number.control_blinds_living_room_door_cooldown_night_blinds_position
##End## living_room_door

##Start## kitchen
config_blinds_kitchen:
  name: Config Blinds kitchen
  entities:
    - input_boolean.control_blinds_kitchen_use_pd_on_close
    - input_boolean.control_blinds_kitchen_openblinds
    - input_boolean.control_blinds_kitchen_closeblinds
    - input_boolean.control_blinds_kitchen_cooldown_during_night
    - input_boolean.control_blinds_kitchen_sunsetsunrise
    - input_datetime.control_blinds_kitchen_offset_blinds_up_weekend
    - input_datetime.control_blinds_kitchen_cooldown_during_night_open
    - input_datetime.control_blinds_kitchen_cooldown_during_night_close
    - input_datetime.control_blinds_kitchen_earliest_time_blinds_up
    - input_datetime.control_blinds_kitchen_latest_time_blinds_down
    - input_datetime.control_blinds_kitchen_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_kitchen_openblinds_on_time
    - input_datetime.control_blinds_kitchen_closeblinds_on_time
    - input_number.control_blinds_kitchen_cooldown_night_blinds_position
##End## kitchen

##Start## living_room_window
config_blinds_living_room_window:
  name: Config Blinds living_room_window
  entities:
    - input_boolean.control_blinds_living_room_window_use_pd_on_close
    - input_boolean.control_blinds_living_room_window_openblinds
    - input_boolean.control_blinds_living_room_window_closeblinds
    - input_boolean.control_blinds_living_room_window_cooldown_during_night
    - input_boolean.control_blinds_living_room_window_sunsetsunrise
    - input_datetime.control_blinds_living_room_window_offset_blinds_up_weekend
    - input_datetime.control_blinds_living_room_window_cooldown_during_night_open
    - input_datetime.control_blinds_living_room_window_cooldown_during_night_close
    - input_datetime.control_blinds_living_room_window_earliest_time_blinds_up
    - input_datetime.control_blinds_living_room_window_latest_time_blinds_down
    - input_datetime.control_blinds_living_room_window_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_living_room_window_openblinds_on_time
    - input_datetime.control_blinds_living_room_window_closeblinds_on_time
    - input_number.control_blinds_living_room_window_cooldown_night_blinds_position
##End## living_room_window

##Start## parentsbedroom
config_blinds_parentsbedroom:
  name: Config Blinds parentsbedroom
  entities:
    - input_boolean.control_blinds_parentsbedroom_use_pd_on_close
    - input_boolean.control_blinds_parentsbedroom_openblinds
    - input_boolean.control_blinds_parentsbedroom_closeblinds
    - input_boolean.control_blinds_parentsbedroom_cooldown_during_night
    - input_boolean.control_blinds_parentsbedroom_sunsetsunrise
    - input_datetime.control_blinds_parentsbedroom_offset_blinds_up_weekend
    - input_datetime.control_blinds_parentsbedroom_cooldown_during_night_open
    - input_datetime.control_blinds_parentsbedroom_cooldown_during_night_close
    - input_datetime.control_blinds_parentsbedroom_earliest_time_blinds_up
    - input_datetime.control_blinds_parentsbedroom_latest_time_blinds_down
    - input_datetime.control_blinds_parentsbedroom_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_parentsbedroom_openblinds_on_time
    - input_datetime.control_blinds_parentsbedroom_closeblinds_on_time
    - input_number.control_blinds_parentsbedroom_cooldown_night_blinds_position
##End## parentsbedroom

##Start## guest_room
config_blinds_guest_room:
  name: Config Blinds guest_room
  entities:
    - input_boolean.control_blinds_guest_room_use_pd_on_close
    - input_boolean.control_blinds_guest_room_openblinds
    - input_boolean.control_blinds_guest_room_closeblinds
    - input_boolean.control_blinds_guest_room_cooldown_during_night
    - input_boolean.control_blinds_guest_room_sunsetsunrise
    - input_datetime.control_blinds_guest_room_offset_blinds_up_weekend
    - input_datetime.control_blinds_guest_room_cooldown_during_night_open
    - input_datetime.control_blinds_guest_room_cooldown_during_night_close
    - input_datetime.control_blinds_guest_room_earliest_time_blinds_up
    - input_datetime.control_blinds_guest_room_latest_time_blinds_down
    - input_datetime.control_blinds_guest_room_offset_blinds_down_after_sunset
    - input_datetime.control_blinds_guest_room_openblinds_on_time
    - input_datetime.control_blinds_guest_room_closeblinds_on_time
    - input_number.control_blinds_guest_room_cooldown_night_blinds_position
##End## guest_room

##Start## global
config_blinds_global:
  name: Config Blinds global
  entities:
    - input_boolean.control_blinds_enable_global
    - input_boolean.control_blinds_enable_pd_global
    - input_boolean.control_blinds_enable_cooldown_during_night_global
    - input_boolean.control_blinds_open_all_blinds_global
    - input_boolean.control_blinds_close_all_blinds_global
    - input_boolean.control_blinds_configuration
##End## global

##Start## config_blinds
config_blinds:
  name: Config Blinds
  entities:
    - group.config_blinds_lisacover
    - group.config_blinds_mariecover
    - group.config_blinds_living_room_door
    - group.config_blinds_kitchen
    - group.config_blinds_living_room_window
    - group.config_blinds_parentsbedroom
    - group.config_blinds_guest_room
    - group.config_blinds_global
##End## config_blinds
