##Start## mi_robot_vacuum
config_vacuum_mi_robot_vacuum:
  name: Config vacuum mi_robot_vacuum
  entities:
    - input_boolean.control_vacuum_mi_robot_vacuum_automatic_control
    - input_datetime.control_vacuum_mi_robot_vacuum_start_time_monday
    - input_datetime.control_vacuum_mi_robot_vacuum_start_time_tuesday
    - input_datetime.control_vacuum_mi_robot_vacuum_start_time_wednesday
    - input_datetime.control_vacuum_mi_robot_vacuum_start_time_thursday
    - input_datetime.control_vacuum_mi_robot_vacuum_start_time_friday
    - input_datetime.control_vacuum_mi_robot_vacuum_start_time_saturday
    - input_datetime.control_vacuum_mi_robot_vacuum_start_time_sunday
##End## mi_robot_vacuum

##Start## roborock_vacuum
config_vacuum_roborock_vacuum:
  name: Config vacuum roborock_vacuum
  entities:
    - input_boolean.control_vacuum_roborock_vacuum_automatic_control
    - input_datetime.control_vacuum_roborock_vacuum_start_time_monday
    - input_datetime.control_vacuum_roborock_vacuum_start_time_tuesday
    - input_datetime.control_vacuum_roborock_vacuum_start_time_wednesday
    - input_datetime.control_vacuum_roborock_vacuum_start_time_thursday
    - input_datetime.control_vacuum_roborock_vacuum_start_time_friday
    - input_datetime.control_vacuum_roborock_vacuum_start_time_saturday
    - input_datetime.control_vacuum_roborock_vacuum_start_time_sunday
##End## roborock_vacuum

##Start## global
config_vacuum_global:
  name: Config vacuum global
  entities:
    - input_boolean.control_vacuum_enable_global
    - input_boolean.control_vacuum_configuration
##End## global

##Start## config_vacuum
config_vacuum:
  name: Config Vacuum
  entities:
    - group.config_vacuum_mi_robot_vacuum
    - group.config_vacuum_roborock_vacuum
    - group.config_vacuum_global
##End## config_vacuum

